theme: jekyll-theme-cayman
username: Lorem Ipsum
user_description: Software Engineer at Lorem Ipsum Dolor
user_title: Mauricio Urraco
email: mauriurraco@gmail.com
personal_website: https://mauriciourraco.com